repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        exclude: '\.(pgm|png|jpg|jpeg|mp4|usd|usda)$'
      - id: end-of-file-fixer
        exclude: '\.(pgm|png|jpg|jpeg|mp4|usd|usda)$'
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=2000']
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
