amcl:
  ros__parameters:
    use_sim_time: True
    set_initial_pose: True
bt_navigator:
  ros__parameters:
    use_sim_time: True
controller_server:
  ros__parameters:
    use_sim_time: True
    controller_frequency: 20.0
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      max_vel_x: 0.8
      max_vel_theta: 1.0
      acc_lim_x: 1.0
      acc_lim_theta: 1.5
planner_server:
  ros__parameters:
    use_sim_time: True
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.25
local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: True
      width: 6
      height: 6
      resolution: 0.05
      robot_radius: 0.30
      plugins: ["voxel_layer", "inflation_layer"]
global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: True
      resolution: 0.05
      robot_radius: 0.30
      plugins: ["static_layer", "inflation_layer"]
